file.input:
  desjardins: tabula.csv
  td: accountactivity.csv

desjardins-merchant:
  matchRegex:
    '[JEAN COUTU]': JEAN COUTU
    '[ALIMENTATION IAN]': METRO
    SAQ: SAQ
    SHELL: SHELL
    '[IGA EXTRA]': IGA
    PIAZZETTA: PIAZZETTA

  categories:
    '[JEAN COUTU]' : Pharmacie
    METRO: Epicerie
    IGA: Epicerie
    PIAZZETTA: Restaurant

td-transaction:
  matchRegex:
    COSTCO : VARIABLE
    '[FRAIS MENSUEL COMPTE]' : FIXE
    '[Envoi - VFC]': IGNORE
    '[TFR-DE]': IGNORE
    '[TFR-A]': IGNORE
    '[Recept - VFC]' : IGNORE