file.input:
  desjardins: tabulaDesjardinsInfinitePrivilege.csv
  td: accountactivity6478799.csv,accountactivity6479221.csv,accountactivity3296586.csv

startDate: 2022-09-26

desjardins-merchant:
  matchRegex:
    '[JEAN COUTU]': JEAN COUTU
    '[ALIMENTATION IAN]': METRO
    SAQ: SAQ
    SHELL: SHELL
    '[IGA EXTRA]': IGA
    PIAZZETTA: PIAZZETTA

  categories:
    '[JEAN COUTU]' : Pharmacie
    METRO: Epicerie
    IGA: Epicerie
    PIAZZETTA: Restaurant

td-transaction:
  matchRegex:
    COSTCO : VARIABLE
    '[FRAIS MENSUEL COMPTE]' : FIXE
    '[Envoi - VFC]': IGNORE
    '[TFR-DE]': IGNORE
    '[TFR-A]': IGNORE
    '[TFR-TO]': IGNORE
    '[TFR-FROM]': IGNORE
    '[PYT FRM]': IGNORE
    '[Recept - VFC]' : IGNORE
    '[ARC 202]' : VARIABLE
    '[MRQ 202]' : VARIABLE
    '[PMT A]' : IGNORE
    '[STP A]' : IGNORE
    '[TD Ins/TD Assur]': FIXE
    '[PMT PRET]' : FIXE
    '[SAAQ-IMMATRI]': FIXE
    '[CANVIE-ING]': FIXE
    '[VIDEOTRON LTEE]': FIXE
    SONIC : FIXE
    '[BQE DE MONTREAL PRET]': FIXE
    '[VERSEMENT PRET  PRET]': FIXE
    '[GWL 1115759]': FIXE
    '[HYDRO-QUEBEC]': FIXE
    '[CHQ#]': FIXE
    '[HYDROSOLUTN]': FIXE
    '[SANI SPORT]': FIXE
    INTEREST: VARIABLE